### ISSUE TITLE
Error if host is specified

### ISSUE THREAD

**Issue by ehallvard** [moltin/moltin-request#148]
If I try specifying a host, I get an error.

Example:
```
const client = new MoltinClient({
  client_id: 'some id',
  host: 'api.moltin.com',
});

client
  .get('products')
  .then(console.log)
  .catch(console.error);
```

I get this error:
```
error: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/user/dev/some-project/functions/node_modules/node-fetch/lib/index.js:1299:9)
    at /Users/user/dev/some-project/functions/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at MoltinClient.fetch (/Users/user/dev/some-project/functions/node_modules/node-fetch/lib/index.js:1401:9)
    at MoltinClient.fetch (/Users/user/dev/some-project/functions/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at MoltinClient.<anonymous> (/Users/user/dev/some-project/functions/node_modules/@moltin/request/dist/index.js:136:51)
    at step (/Users/user/dev/some-project/functions/node_modules/@moltin/request/dist/index.js:43:23)
    at Object.next (/Users/user/dev/some-project/functions/node_modules/@moltin/request/dist/index.js:24:53)
    at /Users/user/dev/some-project/functions/node_modules/@moltin/request/dist/index.js:18:71
    at new Promise (<anonymous>)
```

**Comment by ynnoj** [comment]
@ehallvard You'll need to add the `https` prefix: https://github.com/moltin/moltin-request/blob/596ce5bed5a259b84ffde2da3260f78080f7a5cb/src/index.ts#L22

**Comment by ehallvard** [comment]
ah, I see. Thanks!
