### ISSUE TITLE
GET requests fails

### ISSUE THREAD

**Issue by ehallvard** [moltin/moltin-request#64]
After upgrading to the latest version I'm having trouble doing get-requests. It looks like a body is attached to the request which makes it fail. Here's the error I'm getting:

 TypeError: Request with GET/HEAD method cannot have body
       at new Request (/user_code/node_modules/@moltin/request/node_modules/node-fetch/lib/index.js:1191:10)
       at /user_code/node_modules/@moltin/request/node_modules/node-fetch/lib/index.js:1369:19
       at Object.fetch (/user_code/node_modules/@moltin/request/node_modules/node-fetch/lib/index.js:1367:9)
       at Object.fetch (/user_code/node_modules/@moltin/request/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
       at createClient.<anonymous> (/user_code/node_modules/@moltin/request/dist/index.js:89:46)
       at step (/user_code/node_modules/@moltin/request/dist/index.js:43:23)
       at Object.next (/user_code/node_modules/@moltin/request/dist/index.js:24:53)
       at fulfilled (/user_code/node_modules/@moltin/request/dist/index.js:15:58)
       at process._tickDomainCallback (internal/process/next_tick.js:135:7) }"

**Comment by notrab** [comment]
Hi @ehallvard 

Thanks for opening the issue. I'll patch this now.
